/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BakeryIndexRouteImport } from './routes/bakery.index'
import { Route as BakeryShopRouteImport } from './routes/bakery.shop'
import { Route as FruitsIndexRouteImport } from './routes/fruits.index'
import { Route as FruitsShopRouteImport } from './routes/fruits.shop'
import { Route as BakeryProductSlugRouteImport } from './routes/bakery.product.$slug'
import { Route as FruitsProductSlugRouteImport } from './routes/fruits.product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryIndexRoute = BakeryIndexRouteImport.update({
  id: '/bakery/',
  path: '/bakery/',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryShopRoute = BakeryShopRouteImport.update({
  id: '/bakery/shop',
  path: '/bakery/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitsIndexRoute = FruitsIndexRouteImport.update({
  id: '/fruits/',
  path: '/fruits/',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitsShopRoute = FruitsShopRouteImport.update({
  id: '/fruits/shop',
  path: '/fruits/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryProductSlugRoute = BakeryProductSlugRouteImport.update({
  id: '/bakery/product/$slug',
  path: '/bakery/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FruitsProductSlugRoute = FruitsProductSlugRouteImport.update({
  id: '/fruits/product/$slug',
  path: '/fruits/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bakery/shop': typeof BakeryShopRoute
  '/fruits/shop': typeof FruitsShopRoute
  '/bakery/': typeof BakeryIndexRoute
  '/fruits/': typeof FruitsIndexRoute
  '/bakery/product/$slug': typeof BakeryProductSlugRoute
  '/fruits/product/$slug': typeof FruitsProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bakery/shop': typeof BakeryShopRoute
  '/fruits/shop': typeof FruitsShopRoute
  '/bakery': typeof BakeryIndexRoute
  '/fruits': typeof FruitsIndexRoute
  '/bakery/product/$slug': typeof BakeryProductSlugRoute
  '/fruits/product/$slug': typeof FruitsProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/order-success': typeof OrderSuccessRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bakery/shop': typeof BakeryShopRoute
  '/fruits/shop': typeof FruitsShopRoute
  '/bakery/': typeof BakeryIndexRoute
  '/fruits/': typeof FruitsIndexRoute
  '/bakery/product/$slug': typeof BakeryProductSlugRoute
  '/fruits/product/$slug': typeof FruitsProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/sitemap.xml'
    | '/bakery/shop'
    | '/fruits/shop'
    | '/bakery/'
    | '/fruits/'
    | '/bakery/product/$slug'
    | '/fruits/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/sitemap.xml'
    | '/bakery/shop'
    | '/fruits/shop'
    | '/bakery'
    | '/fruits'
    | '/bakery/product/$slug'
    | '/fruits/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/order-success'
    | '/sitemap.xml'
    | '/bakery/shop'
    | '/fruits/shop'
    | '/bakery/'
    | '/fruits/'
    | '/bakery/product/$slug'
    | '/fruits/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BakeryShopRoute: typeof BakeryShopRoute
  FruitsShopRoute: typeof FruitsShopRoute
  BakeryIndexRoute: typeof BakeryIndexRoute
  FruitsIndexRoute: typeof FruitsIndexRoute
  BakeryProductSlugRoute: typeof BakeryProductSlugRoute
  FruitsProductSlugRoute: typeof FruitsProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/': {
      id: '/bakery/'
      path: '/bakery'
      fullPath: '/bakery/'
      preLoaderRoute: typeof BakeryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/shop': {
      id: '/bakery/shop'
      path: '/bakery/shop'
      fullPath: '/bakery/shop'
      preLoaderRoute: typeof BakeryShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruits/': {
      id: '/fruits/'
      path: '/fruits'
      fullPath: '/fruits/'
      preLoaderRoute: typeof FruitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruits/shop': {
      id: '/fruits/shop'
      path: '/fruits/shop'
      fullPath: '/fruits/shop'
      preLoaderRoute: typeof FruitsShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery/product/$slug': {
      id: '/bakery/product/$slug'
      path: '/bakery/product/$slug'
      fullPath: '/bakery/product/$slug'
      preLoaderRoute: typeof BakeryProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fruits/product/$slug': {
      id: '/fruits/product/$slug'
      path: '/fruits/product/$slug'
      fullPath: '/fruits/product/$slug'
      preLoaderRoute: typeof FruitsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BakeryShopRoute: BakeryShopRoute,
  FruitsShopRoute: FruitsShopRoute,
  BakeryIndexRoute: BakeryIndexRoute,
  FruitsIndexRoute: FruitsIndexRoute,
  BakeryProductSlugRoute: BakeryProductSlugRoute,
  FruitsProductSlugRoute: FruitsProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
